name: Auto trigger an Azure Machine Learning job - Liqun

on:
# When a pull request is merges, the pull request is automatically closed. 
# The if_merged job will only run if the pull request was also merged.
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
      
  train:
    if: github.event.pull_request.merged == true # Run only when the PR is merged
    runs-on: ubuntu-latest
    steps:
    
    # Linting and unit tests jobs
    - name: 1. Install Flake8
      run: |
        python -m pip install flake8

    - name: 2. Run linting tests
      run: | 
        flake8 src/model/
    
    - name: 3. Install packages
      run: | 
        python -m pip install pandas
        python -m pip install mlflow
        python -m pip install scikit-learn

    - name: 4. Run unit tests
      run: | 
        python -m pip install pytest
        pytest tests/test_train.py

    # Azure ML job
    - name: 1. Check out repo
      uses: actions/checkout@main
      
    - name: 2. Install az ml extension
      run: az extension add -n ml -y
      
    - name: 3. Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.TESTING_SECRET}}
  
    - name: 4. Run Azure ML Job
      run: az ml job create --file ./src/job.yml --resource-group ReportingTeamML --workspace-name MSLearn-MLOps
